# -*- coding: utf-8 -*-
"""numpy2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187iOuGWDCFv7w1FSjnIZxoAYey-zAjcI
"""

#Vectores son arreglos de una sola dimension. Las matrices son arreglos de dos dimesniones, filas y columnas

import numpy as np

uni=np.array([8,6,5,6,9,5])
print(uni)

"""Matriz"""

matriz=np.array([(5,9,8,5,5),(8,9,6,5,4),(8,9,6,5,4),(8,9,6,5,4),(8,9,6,5,4)])
print(matriz)

"""Matriz aleatorios random"""

aleat=np.random.random((5,4))
print(aleat)

#un solo valor

full=np.full((3,5),78)
print(full)

print(full.dtype)

#Cambiar tamaño y distribucion de la matriz
a=full.reshape(5,3)
print(a)

print(a[4,2])

"""Mostrar infromacion estadistica de nuestra matriz

"""

print(aleat)
print('Media')
print(aleat.mean())
print(aleat.min())
print(aleat.max())
print(aleat.sum())