# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1636r7zsl1wBImwkzL1mSbU-D_xJHqFCr

**Numpy**

Crear y modificar matrices y hacer operaciones sobre ella
"""

import numpy as np

lista=[25,12,15,15,12,18]
vector=np.array(lista)
print(vector)
#sumarle 1 unidad a cada uno de los datos
print(vector+1)
print(vector*2)
print(vector+2)

print(np.sum(vector))
print(np.mean(vector))
print(vector+vector)

vector2=np.array([1,2,8,4,7,-8])
print(vector2)
print(vector+vector2)

"""**Matrices**

"""

identidad=np.identity(4).astype(int)
print(identidad)
print(np.sum(identidad))

np.zeros((5,20))

np.ones((5,2))

"""Indices en Numpy"""

print(vector[3])
print(identidad[2:3])

vector3=np.zeros((4))+3
print(vector3)

"""Vectores son arreglos de una sola dimension. Las matrices son arreglos de dos dimesniones, filas y columnas"""

