# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybvNI6V1vajWo2zz_IaJ6nnpeK6oS9CE

Taller Librerias de Python

Vamos a realizar una in troduccion a algunas de las librerias de Python para el procesamiento de los datos

- Pandas
- Numpy
- Matplotlib
- Seaborn

1 - Pandas

Maneja los dartos de forma tabular, se le denomina DataFRAME (cOMPUESTO POR FILAS Y COLUMNAS), para hacer uso de esta libreria debemos imnportarla:
"""

import pandas as pd

"""Para crear nuestro primer Data Frame, debo hacer uso de los diccionarios de Pyhton, dentro de los diccionarios vamos a crar las listas que contendran los elemnetos de mi tabla"""

notaSemillero=pd.DataFrame({'Nombres':['pedro','darden','leidy','luis','martha','andrea','carlos','felipe','andres','julian'],'Semestre':[10,9,7,8,10,9,10,8,9,8]})
print(notaSemillero)

"""Podemos incluir columnas adicionales a nuestro dataframe haciendo uso del metodo operador []"""

notaSemillero['Nota1']= 3
notaSemillero

"""Añadir datos diferentes para cada fila"""

notaSemillero['Nota2']=[3.1,4.2,3.3,4.5,4,4,3.8,5,4,3.1]
notaSemillero

"""pANDAS NOS PROVEE DE VARIOS METODOS PARA AGREGAR COLUMNAS A NUESTRA TABLA

- insert()
- assign()
- loc()

"""

notaSemillero.insert(4,'Ciudad',['Manizales','Pereira','Armenia','Cordoba','Cali','Popayan','Manizales','Pereira','Manizales','Popayan'])
notaSemillero

notaSemillero=notaSemillero.assign(Departamento=['Caldas','Risaralda','Quindio','Nariño','Valle del Cauca','Valle','Caldas','Risaralda','Caldas','Valle'])
notaSemillero

"""Para añadir filas, loc[index] y el append"""

#Para este caso debemos conocer la posicionpara nuestra fila

notaSemillero.loc[10]=['lucia',7,4.5,3.5,'Armenia','Quindio']
notaSemillero.loc[3]=['Carolina',7,4.5,3.5,'Armenia','Quindio']
notaSemillero.loc[13]=['Maria',7,4.5,3.5,'Armenia','Quindio']
notaSemillero

"""metodo appen, con este puedo omitir el indice  ignore_index=True"""

notaSemillero=notaSemillero.append({'Nombres':'Mario','Semestre':9,'Nota1':3.8,'Nota2':4,'Ciudad':'Armenia','Departamento':'Quindio'},ignore_index=True)
notaSemillero

"""Modificar Datos en mi dataframe, funcion iloc, pasarle como parametros la posicion del dato y el valor a reemplazar"""

notaSemillero.iloc[5,4]='Cartago'
notaSemillero

"""Filtros , pandas nos permite realiar filtro por una o varias columnas

"""

df1=(notaSemillero[['Nota1','Nota2']])
print(df1)

print(notaSemillero)

#Imprimir filas, paso los indices en una lista haciendo uso del metodo iloc
print(notaSemillero.iloc[[2,3,8,9]])

"""print(notaSemillero.info())

"""

print(notaSemillero.info())

df3=notaSemillero.append({'Nombres':'carmen'},ignore_index=True)
df3

print(df3.info())

"""Eliminar nulos NaN, dropna, """

print(df3.dropna())

"""Reemplazar valores en cada columna incluyendo los datos en un diccionario"""

df4=(df3.fillna('reemplazar'))
#df4=(df3.fillna({'Semestre':'8','Nota1':'3'}))
df4

print(df4.info())

print(df3.describe())

print(df3.info())

print(df3)

df3=df3.fillna({'Semestre':'9','Nota1':3,'Nota2':3.5,'Ciudad':'Cali','Departamento':'Valle del Cauca'})
df3

"""Filtros con condicionales"""

filtro=(df3[(df3['Ciudad']=='Manizales')])
filtro

filtrocondicional=df3[(df3['Ciudad']=='Manizales')&(df3['Semestre']==9)&(df3['Nota1']==4)]
filtrocondicional

"""Crear columnas calculadas"""

df3['Nota Final']=(df3['Nota1']+df3['Nota2'])/2
df3

def agregar(fila):
  promedio=(fila['Nota1']+fila['Nota2'])/2
  return promedio
df3['Promedio']=df3.apply(agregar, axis=1)

df3

"""Agrupación de datos, groupby"""

agrupar=df3.groupby('Departamento').mean()

agrupar

"""Graficación"""

#Importo la libreria mATPLOTLIB
import matplotlib.pyplot as plt

#Notas por departamento
agrupar['Nota Final'].plot(kind='bar')
plt.title('Notas por Departamento')
plt.show()
#grafica por Ciudad

"""Grafico de dispersion"""

df3.plot(kind='scatter', x='Semestre', y='Nota Final')
plt.show()

"""Grafica Lineal"""

agrupar['Nota Final'].plot()
plt.title('Grafica Lineal')
plt.show()

"""**Taller**

•	Crear un DataFrame que contenga las ventas realizadas por una surtidora, deberán agregar por lo menos 6 productos, cada uno con su respectivo valor de compra y valor de venta. Además el Dataframe deberá contener  una columna que indique la cantidad de unidades por producto y otra con la cantidad de unidades vendidas. Pueden agregar la demás información que ustedes consideren de utilidad
•	Deberán aplicar los métodos y funcionalidades aprendidas con respecto a Pandas y graficar lo que consideren relevante con su análisis 

"""